brendan_labels = [
    { "name": "1Password", "search_terms": ["@1password.com"] },
    { "name": "AirBnb", "search_terms": ["@airbnb.com"] },
    { "name": "Amazon Gift Cards", "search_terms": ["gc-orders", "giftcardsales@giftcards.amazon.com"] },
    { "name": "Amazon", "search_terms": ["@amazon.com", "@audible.com", "@primevideo.com", "@onemedical.com", "wholefoodsmarket.com", "chick-fil-a.com"], "avoid": ["gc-orders", "giftcardsales@giftcards.amazon.com"] },
    { "name": "American Express", "search_terms": ["americanexpress.com"] },
    { "name": "Anytime Mailbox", "search_terms": ["PostNet TX221"] },
    { "name": "Apple", "search_terms": [".apple.com", "Your receipt from Apple", "Find My app"], "avoid": ["FemFast", "Mavely"] },
    { "name": "Bali Direct", "search_terms": ["@balidirectstore.com", "Bali Direct"] },
    { "name": "Bank Of America", "search_terms": [".bankofamerica.com"] },
    { "name": "Barclays", "search_terms": [".barclaysus.com"] },
    { "name": "Booking.com", "search_terms": ["@booking.com"] },
    { "name": "CapitalOne", "search_terms": [".capitalone.com", "capitalonebooking.com"] },
    { "name": "Chase", "search_terms": [".chase.com"]},
    { "name": "Citi", "search_terms": [".citi.com"] },
    { "name": "Code", "search_terms": ["github.com", "udemy.com", "npmjs.com", "heroku.com", "docker.com", "figma.com", "githubsupport.com", "wetransfer.com",  "warp.dev", "udemymail.com", "gitbook.com", "mongodb.com", "fig.io", "openai.com", "squarespace.com", "meta.com", "anthropic.com", "Stewart Lynch", "@expo.dev", "agorapulse.com"] },
    { "name": "CycleShare", "search_terms": ["@docomo-cycle.jp"]},
    { "name": "Dropbox", "search_terms": ["@dropbox.com"]},
    { "name": "Enterprise", "search_terms": ["enterprise.com"] },
    { "name": "ESPN", "search_terms": ["espn.com", "espnmail.com"] },
    { "name": "FemFast", "search_terms": ["FemFast"] },
    { "name": "Flights", "avoid": ["alerts@services.barclaysus.com", "citicards@"], "search_terms": ["aa.com", "flightconnections.com", "spirit-airlines.com", "united.com", "delta.com", "aircanada.ca", "avianca.com", "jetblue.com", "flyasiana.com", "egyptair.com", "aerolineas.com.ar", "tap.pt", "finnair.com", "latam.com", "singaporeair.com", "flycemair.co.za", "voeazul.com.br", "ana.co.jp", "capitalonebooking.com", "vietjetair.com", "expedia.com", "flyaircairo.com", "citilink-notification.com", "flybreeze.com", "transnusa.co.id", "omio.com", "flytap.com", "philippineairlines.com", "hawaiianair", "dublinairport.com", "airhelp.com", "neosair.it", "evaair.com", "airasia.com", "citilink-indonesia.com", "aircanada.com", "cathaypacific.com", "jetstar.com", "mycebupacific.com", "aerlingus.com", "alaskaair.com", "spirit.com", "copaair.com", "aegeanair.com", "transavia.com", "ryanair.com", "vueling.com", "easyjet.com", "turkishairlines.com", "airasia.com", "vueling.com", "flyscoot.com"] },
    { "name": "Freedive", "search_terms": ["@skool.com"] },
    { "name": "Games", "search_terms": ["@chess.com"] },
    { "name": "Gojek", "search_terms": ["gojek.com", "go-jek.com", "go-pay.co.id"] },
    { "name": "Google", "search_terms": ["@google.com", "analytics-google.com", "CloudPlatform-google.com", "domains-google.com", "accounts.google.com"], "avoid": ["googleplay-google.com", "Zeit Calendar"] },
    { "name": "Google Play", "search_terms": ["googleplay-google.com"] },
    { "name": "Grab", "search_terms": ["@grab.com"] },
    { "name": "HelloCycling", "search_terms": ["@hellocycling.jp"] },
    { "name": "Japan Trip", "search_terms": [] },
    { "name": "JapanesePod101", "search_terms": ["@japanesepod101.com"] },
    { "name": "LinkedIn", "search_terms": ["@linkedin.com"] },
    { "name": "Mantra", "search_terms": ["Mantra Wellness Center"] },
    { "name": "Mavely", "search_terms": ["Mavely", "MyFavoriteThings"] },
    { "name": "Money", "search_terms": ["intuit.com", "experian.com", "revolut.com", "t-mobile.com", "sofi.org", "square.com", "ovo.co.id", "track1099.com", "crypto.com", "transunion.com", "sofi.com", "vanguard.com", ".wellsfargo.com", "financialaidantitrustsettlement.com", "@ovo.id", "freetaxusa.com"] },
    { "name": "Orders", "search_terms": ["peacocktv.com", "umrelief.org", "Rejuvie Clinic", "regaltickets.com", "amctheatres.com", "btmcinemas.com", "independentpicturehouse.org", "shopmoment.com", "starbucks.com", "@islandorganicsbali.com", "@mobal.com", "@mail.shopee.co.id"] },
    { "name": "Passwords", "search_terms": ["disneyaccount.com", "accountprotection.microsoft.com", "new login", "confirm your email address"] },
    { "name": "People", "search_terms": ["Jarred Kotzin from Almost a musing", "@18birdies-updates.com"] },
    { "name": "Permata", "search_terms": ["@permatabank.co.id"] },
    { "name": "Ramah", "search_terms": ["@ramahgolfbali.com"] },
    { "name": "Recruiters", "search_terms": ["@toptal.com"] },
    { "name": "Rythm Health", "search_terms": ["@rythmhealth.com"] },
    { "name": "Robinhood", "search_terms": ["@robinhood.com"] },
    { "name": "Support", "search_terms": [] },
    { "name": "Sports", "search_terms": ["fantasypros.com", "guillotineleagues.com", "udisc.com", "@18birdies-updates.com"] },
    { "name": "Timeleft", "search_terms": ["@timeleft.com"] },
    { "name": "Travel", "search_terms": ["imglobal.com", "prioritypass.com", "holafly.com", "qeeq.com", "hertz.com", "europcar.com", "global-rent-a-car.pt", "avisbudget.com", "agoda.com", "starlink.com", "kakaocorp.com", "mobal.com", "omanair_reservations"] },
    { "name": "Trip.com", "search_terms": ["@trip.com"] },
    { "name": "Uber", "search_terms": ["@uber.com", "lyftmail.com", "@mgx.cabify.com"] },
    { "name": "USAA", "search_terms": ["usaa.com"] },
    { "name": "Venmo", "search_terms": ["venmo.com", "synchronybank.com", "synchronyfinancial.com"] },
    { "name": "Vipassana", "search_terms": ["dhamma.org"] },
    { "name": "Wise", "search_terms": ["wise.com"] },
    { "name": "Yahoo", "search_terms": ["cc.yahoo-inc.com"] },
    { "name": "Yoga", "search_terms": ["markrobberds.com"] },
    { "name": "YouTube", "search_terms": ["@youtube.com"] },
]